import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/utils/cn";
import { Inter } from "next/font/google";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning className={`${inter.variable}`}>
      <body className={cn("flex bg-background  min-h-screen flex-col font-inter antialiased")}>
        <main className="mb-auto">{children}</main>
      </body>
    </html>
  );
}
